name: Main

on:
  push:
    branches: main
  
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:

jobs:
  generate_snk:
    name: Generates a snake game
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Generates snake
      uses: Platane/snk@v2.1.0
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/snake-github-profile.svg?palette=github-dark&color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
    
    - name: Push the output
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
